# -*- coding: utf-8 -*-
"""Project Outline.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/YBIFoundation/Fundamental/blob/main/Project_Outline.ipynb

# **Hand Written Digit Prediction - Classification Analysis**

-------------

## **Objective**

Handwritten digit prediction is a classic machine learning project where the goal is to classify images of handwritten digits into their respective categories (0 to 9). In this response, I'll provide you with a high-level overview of the steps involved in creating a classification analysis project for handwritten digit prediction in Python.

## **Data Source**

## **Import Library**
"""

import tensorflow as tf

"""## **Import Data**"""

from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Flatten
from tensorflow.keras.utils import to_categorical

"""## **Describe Data**"""



"""## **Data Visualization**"""



"""## **Data Preprocessing**"""

x_train = x_train.reshape(-1, 28, 28, 1) / 255.0
x_test = x_test.reshape(-1, 28, 28, 1) / 255.0
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

"""## **Define Target Variable (y) and Feature Variables (X)**"""



"""## **Train Test Split**"""



"""## **Modeling**"""

model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5, batch_size=32)

"""## **Model Evaluation**"""

loss, accuracy = model.evaluate(x_test, y_test)
print(f'Test accuracy: {accuracy}')

"""## **Prediction**"""



"""## **Explaination**

If you plan to use the model in real-world applications, you can deploy it using various methods, such as creating a web application or integrating it into other software systems.
"""